import type { Issue, Product } from "./types";

const t = (iso: string) => iso;

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-pub",
    slug: "my_publishing",
    name: "Mangu Publishing",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "my_publishing",
    homepage: "https://manguprojectz.vercel.app",
    money_note: "House command center. Books to market.",
    created_at: t("2026-01-17T00:13:47Z"),
  },
  {
    id: "p-tees",
    slug: "madcaptees",
    name: "Madcap Tees",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "madcaptees",
    homepage: "https://madcaptees.vercel.app",
    money_note: "Storefront. Graphic tees.",
    created_at: t("2026-06-08T18:25:57Z"),
  },
  {
    id: "p-hathor",
    slug: "hathor-red",
    name: "Hathor Red",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "hathor-red",
    homepage: null,
    money_note: "Music tool.",
    created_at: t("2025-12-29T10:22:38Z"),
  },
  {
    id: "p-qcash",
    slug: "q_cash",
    name: "Q Cash",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "q_cash",
    homepage: null,
    money_note: "Payments experiment with a live path.",
    created_at: t("2026-02-18T22:40:10Z"),
  },
  {
    id: "p-chambers",
    slug: "chambers-ai",
    name: "Chambers",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "chambers-ai",
    homepage: null,
    money_note: "Resume engine. Tokens live here first.",
    created_at: t("2026-06-24T10:54:55Z"),
  },
  {
    id: "p-alice",
    slug: "alice_chains",
    name: "Alice Chains",
    engine_tag: "cash-engine",
    github_owner: "Mangu-Platforms",
    github_repo: "alice_chains",
    homepage: "https://alice-chains.vercel.app",
    money_note: "Named agent runtime.",
    created_at: t("2026-02-09T11:43:36Z"),
  },
  {
    id: "p-andromeda",
    slug: "andromeda",
    name: "Andromeda",
    engine_tag: "lab",
    github_owner: "Mangu-Platforms",
    github_repo: "andromeda",
    homepage: "https://web-fawn-eta-86.vercel.app",
    money_note: "Agent product lab.",
    created_at: t("2026-08-20T10:01:31Z"),
  },
  {
    id: "p-acx",
    slug: "acx-city",
    name: "ACX City",
    engine_tag: "lab",
    github_owner: "Mangu-Platforms",
    github_repo: "acx-city",
    homepage: "https://acx-city.vercel.app",
    money_note: "City sim / narrative lab.",
    created_at: t("2026-07-24T08:51:01Z"),
  },
  {
    id: "p-cashmere",
    slug: "cashmere-thoughts",
    name: "Cashmere Thoughts",
    engine_tag: "lab",
    github_owner: "Mangu-Platforms",
    github_repo: "cashmere-thoughts",
    homepage: "https://cashmere-thoughts.vercel.app",
    money_note: "Prose lab.",
    created_at: t("2026-08-13T12:59:39Z"),
  },
  {
    id: "p-book1",
    slug: "book1_assign",
    name: "Book 1 Assign",
    engine_tag: "lab",
    github_owner: "Mangu-Platforms",
    github_repo: "book1_assign",
    homepage: "https://book1-assign.vercel.app",
    money_note: "Assignment surface for the book engine.",
    created_at: t("2026-07-18T19:06:06Z"),
  },
  {
    id: "p-boss",
    slug: "boss_pm-tool1",
    name: "Boss PM",
    engine_tag: "lab",
    github_owner: "Mangu-Platforms",
    github_repo: "boss_pm-tool1",
    homepage: null,
    money_note: "This tool. Earns the cash-engine tag when sync is boring.",
    created_at: t("2026-08-25T22:00:00Z"),
  },
];

export const SEED_ISSUES: Issue[] = [
  {
    id: "i-1",
    product_id: "p-pub",
    title: "Ship synopsis-to-manuscript path for title 04",
    body: "Operator path only. No new modules.",
    status: "doing",
    priority: "high",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "alice",
    cost_cap_cents: 800,
    due_on: "2026-08-29",
    created_at: t("2026-08-20T12:00:00Z"),
    updated_at: t("2026-08-25T12:00:00Z"),
  },
  {
    id: "i-2",
    product_id: "p-pub",
    title: "Goodreads rank-16 block: write the postmortem",
    body: "Facts only. What the CI actually saw.",
    status: "open",
    priority: "medium",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: "2026-08-27",
    created_at: t("2026-08-21T12:00:00Z"),
    updated_at: t("2026-08-21T12:00:00Z"),
  },
  {
    id: "i-3",
    product_id: "p-alice",
    title: "Swarm a cover-letter variant set, cap $4",
    body: "Five variants. Stop at cap.",
    status: "open",
    priority: "medium",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "swarm",
    cost_cap_cents: 400,
    due_on: null,
    created_at: t("2026-08-22T12:00:00Z"),
    updated_at: t("2026-08-22T12:00:00Z"),
  },
  {
    id: "i-4",
    product_id: "p-tees",
    title: "Fix checkout empty-cart flash",
    body: "Storefront cash path.",
    status: "open",
    priority: "critical",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: null,
    created_at: t("2026-08-18T12:00:00Z"),
    updated_at: t("2026-08-18T12:00:00Z"),
  },
  {
    id: "i-5",
    product_id: "p-boss",
    title: "Prove GitHub one-way sync on my_publishing",
    body: "Claim 3. No Gantt until this is green.",
    status: "doing",
    priority: "high",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "swarm",
    cost_cap_cents: 300,
    due_on: "2026-08-26",
    created_at: t("2026-08-25T18:00:00Z"),
    updated_at: t("2026-08-25T18:00:00Z"),
  },
  {
    id: "i-6",
    product_id: "p-chambers",
    title: "Token usage analytics dashboard",
    body: "Show daily/weekly token consumption per resume generated.",
    status: "backlog",
    priority: "medium",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "alice",
    cost_cap_cents: 600,
    due_on: "2026-09-05",
    created_at: t("2026-08-23T14:00:00Z"),
    updated_at: t("2026-08-23T14:00:00Z"),
  },
  {
    id: "i-7",
    product_id: "p-hathor",
    title: "Audio waveform rendering in player component",
    body: "Web Audio API. Render to canvas on load.",
    status: "open",
    priority: "high",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: "2026-09-01",
    created_at: t("2026-08-22T09:00:00Z"),
    updated_at: t("2026-08-22T09:00:00Z"),
  },
  {
    id: "i-8",
    product_id: "p-qcash",
    title: "Stripe webhook signature verification",
    body: "Must verify signatures before processing events.",
    status: "doing",
    priority: "critical",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: "2026-08-27",
    created_at: t("2026-08-24T16:00:00Z"),
    updated_at: t("2026-08-25T10:00:00Z"),
  },
  {
    id: "i-9",
    product_id: "p-andromeda",
    title: "Multi-agent orchestration prototype",
    body: "Spawn sub-agents from a parent. Track lineage.",
    status: "open",
    priority: "high",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "swarm",
    cost_cap_cents: 1200,
    due_on: "2026-09-10",
    created_at: t("2026-08-24T11:00:00Z"),
    updated_at: t("2026-08-24T11:00:00Z"),
  },
  {
    id: "i-10",
    product_id: "p-acx",
    title: "Narrative branching engine - save system",
    body: "Player choices create branches. Serialize state to IndexedDB.",
    status: "backlog",
    priority: "low",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: null,
    created_at: t("2026-08-20T08:00:00Z"),
    updated_at: t("2026-08-20T08:00:00Z"),
  },
  {
    id: "i-11",
    product_id: "p-cashmere",
    title: "Export to EPUB from prose editor",
    body: "Use epub-gen or similar. Preserve styles.",
    status: "open",
    priority: "medium",
    assignee_kind: "agent",
    assignee_user: null,
    agent_name: "alice",
    cost_cap_cents: 500,
    due_on: "2026-09-15",
    created_at: t("2026-08-21T15:00:00Z"),
    updated_at: t("2026-08-21T15:00:00Z"),
  },
  {
    id: "i-12",
    product_id: "p-tees",
    title: "Implement size chart modal with measurements",
    body: "Reduce returns. Show cm/inches toggle.",
    status: "done",
    priority: "medium",
    assignee_kind: "user",
    assignee_user: "operator",
    agent_name: null,
    cost_cap_cents: null,
    due_on: "2026-08-20",
    created_at: t("2026-08-15T12:00:00Z"),
    updated_at: t("2026-08-22T17:00:00Z"),
  },
];
